export const questions = [
  {
    question: "Wer hat HTML efunden?",
    answer_1: "Robbie Williams",
    answer_2: "Lady Gaga",
    answer_3: "Tim Berners-Lee",
    answer_4: "JustinBiber",
    right_answer: 3,
  },
  {
    question: "Was bedeutet HTML?",
    answer_1: "Hyper Markup Language",
    answer_2: "Hypertext Markup Language",
    answer_3: "Hypertext Mark Language",
    answer_4: "Hypertext Markup Listing",
    right_answer: 2,
  },
  {
    question: "Wo für steht das width=90% bei Bildern?",
    answer_1: "Keine antwort ist richtig",
    answer_2: "Bild nimmt 90% des Elternelements.",
    answer_3: "Bild nimmt 90% der Fensterhöhe.",
    answer_4: "Bild nimmt 90% der Fensterbreite.",
    right_answer: 4,
  },
  {
    question: "Wie merken Sie sich die Namen der Attribute?",
    answer_1: "Auswendig Lernen",
    answer_2: "Gar nicht, ich Google",
    answer_3: "Muss ich mir das merken?",
    answer_4: "Was ist ein Attribute?",
    right_answer: 2,
  },
  {
    question: "Welche Farbe ist #0000ff?",
    answer_1: "Blau",
    answer_2: "Grün",
    answer_3: "Gelb",
    answer_4: "Rot",
    right_answer: 1,
  },
];
